---
# You can find the default configuration file with documentation for all
# available fields on the GitHub releases page for each release.
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# FIXME
# - note the blurry box-drawing characters are due to the fact
#   Alacirtty just use the characters from the font directly, intead
#   of replacing them with good fonts
#   check out: https://github.com/alacritty/alacritty/issues/3262
env:
  WINIT_HIDPI_FACTOR: "1.0"
window:
  dynamic_title: false
  dimensions:
    columns: 120
    lines: 30
  decorations: none
  dynamic_padding: true
font:
  size: 12
  normal:
    family: Cascadia Code
  italic:
    family: Cascadia Code Italic
draw_bold_text_with_bright_colors: true
schemes:
  nord: &dark
    primary:
      background: "#2e3440"
      foreground: "#d8dee9"
    cursor:
      text: "#2e3440"
      cursor: "#d8dee9"
    normal:
      black: "#3b4252"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#88c0d0"
      white: "#e5e9f0"
    bright:
      black: "#4c566a"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#8fbcbb"
      white: "#eceff4"
  gruvbox_light: &light
    primary:
      background: "#f2e5bc"
      foreground: "#3c3836"
    cursor:
      text: "#f2e5bc"
      cursor: "#3c3836"
    normal:
      black: "#fbf1c7"
      red: "#cc241d"
      green: "#98971a"
      yellow: "#d79921"
      blue: "#458588"
      magenta: "#b16286"
      cyan: "#689d6a"
      white: "#7c6f64"
    bright:
      black: "#928374"
      red: "#9d0006"
      green: "#79740e"
      yellow: "#b57614"
      blue: "#076678"
      magenta: "#8f3f71"
      cyan: "#427b58"
      white: "#3c3836"
colors: *dark
mouse:
  hide_when_typing: true
selection:
  save_to_clipboard: true
