#! /usr/bin/env bash

set -eu

source ../utils.sh

main() {
  #
  # trigger install functions dynamically
  #
  IFS=$'\n'
  for f in $(declare -F); do
    func_name="${f:11}"

    if [[ "$func_name" = 'install_'* ]]; then
      "$func_name"
    fi
  done
}

install_chrome() {
  if hash google-chrome-stable 2>/dev/null; then
    __.log_info 'Google Chrome is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing Google Chrome...'
  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  if [[ ! -f chrome.deb ]]; then
    wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  fi
  sudo apt install --fix-broken --yes --no-install-recommends /tmp/chrome.deb
}

install_neovim() {
  if hash nvim 2>/dev/null; then
    __.log_info 'neovim is installed, skipping ...'
    return 0
  fi

  __.log_info 'Installing neovim ...'
  sudo add-apt-repository --yes ppa:neovim-ppa/stable
  sudo apt install --fix-broken --yes --no-install-recommends neovim

  # use neovim by default system wide
  sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  sudo update-alternatives --auto vi
  sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
  sudo update-alternatives --auto vim
  sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
  sudo update-alternatives --auto editor
}

install_tlp() {
  if hash tlp 2>/dev/null; then
    __.log_info 'tlp is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing tlp...'
  sudo add-apt-repository --yes ppa:linrunner/tlp
  # https://linrunner.de/tlp/faq/installation.html#ubuntu-how-do-i-prevent-the-installation-of-postfix-as-a-dependency
  sudo apt install --fix-broken --yes --no-install-recommends tlp tlp-rdw ethtool smartmontools
}

install_mainline() {
  if hash mainline 2>/dev/null; then
    __.log_info 'mainline is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing mainline...'
  sudo add-apt-repository --yes ppa:cappelikan/ppa
  sudo apt install --fix-broken --yes --no-install-recommends mainline
}

install_mpv() {
  if hash mpv 2>/dev/null; then
    __.log_info 'mpv is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing mpv...'
  sudo add-apt-repository --yes ppa:mc3man/mpv-tests
  sudo apt install --fix-broken --yes --no-install-recommends mpv
}

install_peek() {
  if hash peek 2>/dev/null; then
    __.log_info 'peek is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing peek...'
  sudo add-apt-repository --yes ppa:peek-developers/stable
  sudo apt install --fix-broken --yes --no-install-recommends peek
}

install_virtualbox() {
  if hash virtualbox 2>/dev/null; then
    __.log_info 'virtualbox is installed, skipping ...'
    return 0
  fi

  __.log_info 'Installing virtualbox ...'
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  sudo add-apt-repository --yes \
    "deb http://download.virtualbox.org/virtualbox/debian \
    $(lsb_release --codename --short) \
    contrib"
  sudo apt update
  sudo apt install --yes --no-install-recommends virtualbox
}

install_htop() {
  if hash htop 2>/dev/null; then
    __.log_info 'htop is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing htop...'
  sudo apt install --fix-broken --yes --no-install-recommends htop
}

install_flameshot() {
  if hash flameshot 2>/dev/null; then
    __.log_info 'flameshot is installed, skipping...'
    return 0
  fi

  __.log_info 'Installing flameshot...'
  sudo apt install --fix-broken --yes --no-install-recommends flameshot
}

main

# vim: set autoindent expandtab nowrap number textwidth=119 tabstop=2 shiftwidth=2 :
