#! /usr/bin/env bash

set -eu

source ../utils.sh


# TODO
# - should load environment variables from ../../config/bash/
main(){
  install_prerequisites
  set_up_system_directories
}

install_prerequisites(){
  # 
  # Prerequisites
  #
  # some of the apps below are needed during the installation period, e.g.:
  # git, stow
  # could be override once other software managers are installed
  #
  __.log_info 'Checking prerequisites...'
  local prerequisites=''

  for app in \
    build-essential \
    git \
    net-tools \
    openssh-server \
    software-properties-common \
    stow;\
  do
    if [[ -z "$(dpkg --get-selections "$app" 2>/dev/null)" ]]; then
      prerequisites+="$app "
    fi
  done

  if [[ -z "$prerequisites" ]]; then
    __.log_info 'Prerequisites are satisified, skipping...'
  else
    __.log_info 'Installing missing prerequisites...'
    sudo apt update
    # we want $prerequisites to be splat here
    sudo apt install --yes --no-install-recommends $prerequisites
  fi
}

set_up_system_directories(){
  sudo mkdir --parents /sandbox
  sudo chown "$USER:$USER" /sandbox
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
