#! /usr/bin/env bash

set -eu


# TODO
# - should load environment variables from ../../config/bash/
main(){
  check_system_config
  install_prerequisites
}

check_system_config(){
  if [[ ! -w "$INSTALLATION_PREFIX" ]]; then
    l "INSTALLATION_PREFIX: $INSTALLATION_PREFIX does not exists or"
    l "you don't have write permission, please double check!"
    exit 1
  fi
}


install_prerequisites(){
  # 
  # Prerequisites
  #
  # some of the apps below are needed during the installation period, e.g.:
  # git, stow
  # could be override once other software managers are installed
  #
  l 'Checking prerequisites...'
  local prerequisites=''

  for app in build-essential git software-properties-common stow; do
    if [[ -z "$(dpkg --get-selections "$app" 2>/dev/null)" ]]; then
      prerequisites+="$app "
    fi
  done

  if [[ -z "$prerequisites" ]]; then
    l 'Prerequisites are satisified, skipping...'
  else
    l 'Installing missing prerequisites...'
    sudo apt update
    # we want $prerequisites to be splat here
    sudo apt install --yes --no-install-recommends $prerequisites
  fi
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
