#! /usr/bin/env bash

set -eu

source ../../config/bash/bash.env
source ../utils.sh

__.log_info "Using prefix: ${__prefix_conda:?}"

main(){
  install_conda
  create_conda_envs
}

install_conda(){
  if hash conda 2>/dev/null; then
    __.log_info 'conda is installed, skipping...'
    conda --version
    return 0
  fi

  __.log_info 'Installing conda...'
  local conda_script_path='/tmp/conda.sh'
  if [[ ! -f "$conda_script_path" ]]; then
      wget -O "$conda_script_path" https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  fi

  chmod +x "$conda_script_path"
  "$conda_script_path" -b -p "$__prefix_conda"
  conda --version
}

create_conda_envs(){

  if [[ -d "${__prefix_conda:?}/envs/py3" ]]; then
    __.log_info 'Conda env py3 already exists, skipping...'
  else
    __.log_info 'Creating conda env py3...'
    conda create --yes --name py3 python=3
  fi
  (
    "${__prefix_conda:?}/envs/py3/bin/pip" install --upgrade pynvim
  )

  if [[ -d "${__prefix_conda:?}/envs/py2" ]]; then
    __.log_info 'Conda env py2 already exists, skipping...'
  else
    __.log_info 'Creating conda env py2...'
    conda create --yes --name py2 python=2
  fi
  (
    "${__prefix_conda:?}/envs/py2/bin/pip" install --upgrade pynvim
  )
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
