#! /usr/bin/env bash

set -eu

source ../../config/bash/bash.env
source ../utils.sh

__.log_info "Using prefix: ${__prefix_conda:?}"

main(){
  install_conda
  create_conda_envs
}

install_conda(){
  if hash conda 2>/dev/null; then
    __.log_info 'conda is installed, skipping...'
    conda --version
    return 0
  fi

  __.log_info 'Installing conda...'
  local conda_script_path='/tmp/conda.sh'
  if [[ ! -f "$conda_script_path" ]]; then
      wget -O "$conda_script_path" https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  fi

  chmod +x "$conda_script_path"
  "$conda_script_path" -b -p "$__prefix_conda"
  conda --version
}

create_conda_envs(){
  __.log_info 'Creating conda envs...'

  if [[ ! -d "${__prefix_conda:?}/envs/py3" ]]; then
    conda create --name py3 python=3
  fi

  if [[ ! -d "${__prefix_conda:?}/envs/py2" ]]; then
    conda create --name py2 python=2
  fi
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
