#! /usr/bin/env bash

set -eu

source ../utils.sh

main(){
  install_docker
}

install_docker(){
  if hash docker 2>/dev/null; then
    __.log_info 'docker is installed, skipping ...'
    return 0
  fi

  __.log_info 'Installing docker ...'
  getent group docker > /dev/null || sudo groupadd docker
  sudo usermod --append --groups docker "$USER"

  #
  # group hack without logout
  #
  newgrp docker
  newgrp "$USER"
  __.log_warning "Added $USER to docker group, you need to logout and log in again to make it permanent."


  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository --yes \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release --codename --short) \
     stable"

  sudo apt-get install --yes --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

  sudo apt-get install --yes --no-install-recommends \
    docker-ce \
    docker-ce-cli \
    containerd.io
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
