#! /usr/bin/env bash

set -eu

source ../../config/bash/bash.env
source ../utils.sh

__.log_info "Using prefix: ${__prefix_nvm:?}"

main(){
  install_nvm
  install_node
  install_node_apps
}

#
# node/npm via nvm
#
# migrate global packages while installing
# nvm install node --reinstall-packages-from=node
#
install_nvm(){
  if hash nvm 2>/dev/null; then
    __.log_info 'nvm is installed, skipping...'
    nvm --version
    return 0
  fi

  if [[ -f "${__prefix_nvm:?}/nvm.sh" ]]; then
    source "${__prefix_nvm:?}/nvm.sh" --no-use
    __.log_info 'nvm is installed but not sourced, skipping...'
    nvm --version
    return 0
  fi

  __.log_info 'Installing nvm...'
  (
    git clone https://github.com/nvm-sh/nvm.git "$__prefix_nvm"
    cd "$__prefix_nvm"
    git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
  )
  # shellcheck source=/sandbox/.nvm/nvm.sh
  source "${__prefix_nvm:?}/nvm.sh" --no-use

  __.log_info '>>>>>>>>>>>>> Checking nvm version'
    # HACK nvm returns non-zero code: https://github.com/nvm-sh/nvm/issues/993
  __.log_info $(nvm --version)
}

install_node(){
  __.log_info 'installing node'

  if [[ $(command -v node) == *'nvm'* ]]; then
    __.log_info 'node is installed, skipping...'
    return 0
  fi

  __.log_info 'installing latest lts node...'

  # XXX /sandbox/vincent/.nvm/nvm.sh may raise unbound variable error when using bash 5
  set +u
  nvm install --lts
  set -u
}

install_node_apps(){
  #
  # also checkout ./linuxbrew
  # XXX some packages are available both in npm and brew, prefer npm in this case
  #

  npm install --global npm

  # Dev essentials
  npm install --global neovim     # neovim js plugin
  npm install --global typescript # TypeScript support
  npm install --global prettier   # Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML

  # Linters
  npm install --global markdownlint         # Markdown
  npm install --global textlint             # General text
  npm install --global write-good           # Better writting
  npm install --global bash-language-server # lsp for bash, see also shellcheck

  # CLI essentials
  npm install --global tldr           # Simplified and community-driven man pages
  npm install --global git-tip        # git tip of the day
  npm install --global diff-so-fancy  # better git diff

  # Web dev tools
  npm install --global wscat  # handy websocket cli for testing
}

main

# vim: set autoindent expandtab nowrap number textwidth=119 tabstop=2 shiftwidth=2 :
