#! /usr/bin/env bash

set -eu

source ../../config/bash/bash.env
source ../utils.sh

__.log_info "Using prefix: ${__prefix_nvm:?}"

main(){
  install_nvm
  install_node
  install_node_apps
}

#
# node/npm via nvm
#
# migrate global packages while installing
# nvm install node --reinstall-packages-from=node
#
install_nvm(){
  if hash nvm 2>/dev/null; then
    __.log_info 'nvm is installed, skipping...'
    nvm --version
    return 0
  fi

  __.log_info 'Installing nvm...'
  (
    git clone https://github.com/nvm-sh/nvm.git "$__prefix_nvm"
    cd "$__prefix_nvm"
    git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
  )
  # shellcheck source=/sandbox/.nvm/nvm.sh
  source "${__prefix_nvm:?}/nvm.sh" --no-use
  nvm --vesion
}

install_node(){
  if [[ $(command -v node) == *'nvm'* ]]; then
    __.log_info 'node is installed, skipping...'
    return 0
  fi

  __.log_info 'installing latest lts node...'
  nvm install --lts
}

install_node_apps(){
  # upgrade npm first
  npm install --global npm

  # install node.js provider for neovim
  npm install --global neovim

  # man for the impatient
  npm install --global tldr

  # handy websocket cli for testing
  npm install --global wscat

  # better git diff
  npm install --global diff-so-fancy

  # lsp for bash, see also shellcheck
  npm install --global bash-language-server
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
