#! /usr/bin/env bash

set -eu

source ../utils.sh

main(){
  check_system_config
  install_rbenv
  install_ruby
  install_ruby_apps
}

#
# ruby/gem via rbenv
#
# migrate global packages while installing
# rbenv install ruby --reinstall-packages-from=ruby
#
install_rbenv(){
  __.log_warning 'TODO: install rbenv!'
  return 0

  if hash rbenv 2>/dev/null; then
    __.log_info 'rbenv is installed, skipping...'
    return 0
  else
    __rbenv_prefix__="$INSTALLATION_PREFIX/.rbenv"
  fi
}

install_ruby(){
  __.log_warning 'TODO: install rbenv!'
  return 0

  if [[ $(command -v ruby) == *'rbenv'* ]]; then
    __.log_info 'ruby is installed, skipping...'
  else
    __.log_info 'installing latest lts ruby...'
    rbenv install --lts
  fi
}

install_ruby_apps(){
  __.log_warning 'TODO: instal_ruby_apps'
  return 0
}

main

# vim: set autoindent expandtab number textwidth=119 tabstop=2 shiftwidth=2 :
