#!/bin/bash

set_bg()
{
  printf '\x1b[48;2;%s;%s;%sm' "$1" "$2" "$3"
}

reset_output()
{
  echo -en "\x1b[0m\n"
}

__.color.base16()
{
  echo 'Base 16:'
  for i in 0 1; do
    for color in {0..7}; do
      printf "\e[48;5;%sm%5s   \e[0m" $((color + i * 8)) $((color + i * 8))
    done
    reset_output
  done
}

__.color.stripes()
{
  echo "24bit color stripes:"
  for i in {0..255..4}; do
    set_bg $i 0 0
    echo -en " "
  done
  reset_output

  for i in {0..255..4}; do
    set_bg 0 $i 0
    echo -n " "
  done
  reset_output

  for i in {0..255..4}; do
    set_bg 0 0 $i
    echo -n " "
  done
  reset_output

  for i in {0..255..4}; do
    set_bg $i $i $i
    echo -n " "
  done
  reset_output

  for i in {0..255..4}; do
    set_bg 255 $i 0
    echo -n " "
  done
  reset_output

  for i in {255..0..4}; do
    set_bg $i 255 0
    echo -n " "
  done
  reset_output

  for i in {0..255..4}; do
    set_bg 0 255 $i
    echo -n " "
  done
  reset_output

  for i in {255..0..4}; do
    set_bg 0 $i 255
    echo -n " "
  done
  reset_output

  for i in {0..255..4}; do
    set_bg $i 0 255
    echo -n " "
  done
  reset_output

  for i in {255..0..4}; do
    set_bg 255 0 $i
    echo -n " "
  done
  reset_output
}

__.color.fonts()
{
  echo -e "\e[1mbold\e[0m"
  echo -e "\e[3mitalic\e[0m"
  echo -e "\e[4munderline\e[0m"
  echo -e "\e[9mstrikethrough\e[0m"
  echo -e "\e[31mHello World\e[0m"
  echo -e "\e[31mHello World\e[0m"

  echo -e '\e[1mbold\e[22m'
  echo -e '\e[2mdim\e[22m'
  echo -e '\e[3mitalic\e[23m'
  echo -e '\e[4munderline\e[24m'
  echo -e '\e[4:1mthis is also underline (new in 0.52)\e[4:0m'
  echo -e '\e[21mdouble underline (new in 0.52)\e[24m'
  echo -e '\e[4:2mthis is also double underline (new in 0.52)\e[4:0m'
  echo -e '\e[4:3mcurly underline (new in 0.52)\e[4:0m'
  echo -e '\e[5mblink (new in 0.52)\e[25m'
  echo -e '\e[7mreverse\e[27m'
  echo -e '\e[8minvisible\e[28m <- invisible (but copy-pasteable)'
  echo -e '\e[9mstrikethrough\e[29m'
  echo -e '\e[53moverline (new in 0.52)\e[55m'

  echo -e '\e[31mred\e[39m'
  echo -e '\e[91mbright red\e[39m'
  echo -e '\e[38:5:48m256-color, de jure standard (ITU-T T.416)\e[39m'
  echo -e '\e[38;5;48m256-color, de facto standard (commonly used)\e[39m'
  echo -e '\e[38:2::240:143:104mtruecolor, de jure standard (ITU-T T.416) (new in 0.52)\e[39m'
  echo -e '\e[38:2:240:143:104mtruecolor, rarely used incorrect format (might be removed at some point)\e[39m'
  echo -e '\e[38;2;240;143;104mtruecolor, de facto standard (commonly used)\e[39m'

  echo -e '\e[46mcyan background\e[49m'
  echo -e '\e[106mbright cyan background\e[49m'
  echo -e '\e[48:5:42m256-color background, de jure standard (ITU-T T.416)\e[49m'
  echo -e '\e[48;5;42m256-color background, de facto standard (commonly used)\e[49m'
  echo -e '\e[48:2::240:143:104mtruecolor background, de jure standard (ITU-T T.416) (new in 0.52)\e[49m'
  echo -e '\e[48:2:240:143:104mtruecolor background, rarely used incorrect format (might be removed at some point)\e[49m'
  echo -e '\e[48;2;240;143;104mtruecolor background, de facto standard (commonly used)\e[49m'

  echo -e '\e[21m\e[58:5:42m256-color underline (new in 0.52)\e[59m\e[24m'
  echo -e '\e[21m\e[58;5;42m256-color underline (new in 0.52)\e[59m\e[24m'
  echo -e '\e[4:3m\e[58:2::240:143:104mtruecolor underline (new in 0.52) (*)\e[59m\e[4:0m'
  echo -e '\e[4:3m\e[58:2:240:143:104mtruecolor underline (new in 0.52) (might be removed at some point) (*)\e[59m\e[4:0m'
  echo -e '\e[4:3m\e[58;2;240;143;104mtruecolor underline (new in 0.52) (*)\e[59m\e[4:0m'

  for fgbg in 38 48; do # Foreground/Background
    for color in {0..15}; do
      for attr in 0 1 2 3 4 7; do # Attr: normal bold dim italic underline inverted
        color_code="${attr};${fgbg};5;${color}"
        echo -en "\e[${color_code}m ${color_code} \e[0m\t"
      done
      echo #New line
    done
    echo #New line
  done
}
