#! /usr/bin/env bash

if ! hash docker > /dev/null 2>&1; then
  >&2 echo 'no docker detected, skipping addons'
  return 0
fi

__.docker.clean()
{
  docker images prune --filter 'dangling=true'
  docker volume prune --filter 'dangling=true'
}

__.docker.start_plantuml_server()
{
  # TODO
  # - this better be started asynchronously when necessary, e.g.:
  #   - create a container before hand during the provisioning period
  #   - after opened a PlantUML file
  #   - start the container
  #   - docker stop plant_uml whenever a timeout is reached, e.g. 1 hour, or the file is closed?
  #   - actual implementation depends on the speed
  docker run \
    --detach \
    --restart=unless-stopped \
    --publish 12345:8080 \
    --name=plantuml-server \
    plantuml/plantuml-server:jetty
}
