#! /usr/bin/env bash
#
# Any non-trival alias that not straightforward enough need to be functions, because:
#   - functions are more powerful
#   - functions are easy to trace, e.g. declare -F EXAMPLE_FUNCTION
#
shopt -s expand_aliases

alias ......="cd ../../../../.."
alias .....="cd ../../../.."
alias ....="cd ../../.."
alias ...="cd ../.."
alias ..="cd .."
alias c='clear'
alias cp='cp --interactive'
alias df='df --human-readable'
alias du='du -human-readable --total'
alias l='ls'
alias lh='ll --sort=size'
alias ll='ls --format=verbose'
alias ls='ls -C --classify --human-readable --color=auto --group-directories-first'
alias lt='ll --sort=time'
alias mkdir='mkdir --parents --verbose'
alias mv='mv --interactive'
alias sl='ls'  # :(
alias tree='tree -CF'
alias x='cd $XDG_CONFIG_HOME'
