#! /usr/bin/env bash
#
# XDG support hacks :(
#
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"

export GEMRC="$XDG_CONFIG_HOME/ruby/gemrc"
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

#
# My conventions
#

export DEV_REPO_ROOT="${DEV_REPO_ROOT:-/sandbox/$USER/repos}"


# Colour Off
# shellcheck disable=SC2034
COFF="\[\e[0m\]"

#
# Base16 like Colours in convenient naming
#
color_codes=(234 235 240 241 244 245 254 230 3 1 5 4 6 2)
color_names=(BASE03 BASE02 BASE01 BASE00 BASE0 BASE1 BASE2 BASE3 YELLOW RED MAGENTA BLUE CYAN GREEN)
for i in "${!color_names[@]}"; do
  declare  "${color_names[$i]}=\[\e[00;38;5;${color_codes[$i]}m\]"  # Normal
  declare "B${color_names[$i]}=\[\e[01;38;5;${color_codes[$i]}m\]"  # Bold
  declare "U${color_names[$i]}=\[\e[04;38;5;${color_codes[$i]}m\]"  # Underlined
  declare "I${color_names[$i]}=\[\e[07;38;5;${color_codes[$i]}m\]"  # Inverted
done
unset color_codes
unset color_names

# vim: set autoindent tabstop=2 shiftwidth=2 textwidth=79:
