#! /usr/bin/env bash
#
# bash functions loader for noninteractive apps, e.g. vim
#

this_file="${BASH_SOURCE[0]}"
this_dir=$(dirname "$this_file")

# shellcheck source=./addons/conda
source "$this_dir/addons/conda"
# shellcheck source=./addons/misc
source "$this_dir/addons/misc"

# vim: set autoindent tabstop=2 shiftwidth=2 textwidth=79:
