#! /usr/bin/env bash
# FIXME
# - https://google.github.io/styleguide/shellguide.html
# - re-think about the loading logic

#
# bash functions loader for noninteractive apps
#

this_file="${BASH_SOURCE[0]}"
this_dir=$(dirname "$this_file")

# shellcheck source=./addons/conda
source "$this_dir/addons/conda"
# shellcheck source=./addons/misc
source "$this_dir/addons/misc"
