#! /usr/bin/env bash

#
# useful functions for Tmux plugins
#

get_tmux_option()
{
  local option_name="$1"
  local default_option_value="$2"
  local option_value
  option_value=$(tmux show-option -gqv "$option_name")

  if [[ -n "$option_value" ]]; then
    echo "$option_value"
  else
    echo "$default_option_value"
  fi
}

set_tmux_option()
{
  local option_name="$1"
  local option_value="$2"
  local session="$3"

  if [[ -n "$session" ]]; then
    tmux set-option -t "$session" "$option_name" "$option_value"
  else
    tmux set-option -g "$option_name" "$option_value"
  fi
}
