#! /usr/bin/env bash
echo -e "Default \e[39mDefault\e[0m"
echo -e "Default \e[30mBlack\e[0m"
echo -e "Default \e[31mRed\e[0m"
echo -e "Default \e[32mGreen\e[0m"
echo -e "Default \e[33mYellow\e[0m"
echo -e "Default \e[34mBlue\e[0m"
echo -e "Default \e[35mMagenta\e[0m"
echo -e "Default \e[36mCyan\e[0m"
echo -e "Default \e[37mLight gray\e[0m"
echo -e "Default \e[90mDark gray\e[0m"
echo -e "Default \e[91mLight red\e[0m"
echo -e "Default \e[92mLight green\e[0m"
echo -e "Default \e[93mLight yellow\e[0m"
echo -e "Default \e[94mLight blue\e[0m"
echo -e "Default \e[95mLight magenta\e[0m"
echo -e "Default \e[96mLight cyan\e[0m"
echo -e "Default \e[97mWhite\e[0m"

