#!/usr/bin/env sh

#
# ffmpeg is much faster than the combination of scrot + imagemagick
# roughly 300 ms vs 1000 ms
#

image_file=/tmp/screen_lock.png
resolution='3200x1800'
# resolution=$(xdpyinfo | grep dimensions | awk '{print $2}')

# use blur filter
filters='gblur=sigma=8'

# use down sampling and upsampling
# filters='noise=alls=10,scale=iw*.05:-1,scale=iw*20:-1:flags=neighbor'

ffmpeg -y \
  -loglevel 0 \
  -s "$resolution" \
  -f x11grab \
  -i "$DISPLAY" \
  -vframes 1 \
  -vf "$filters" \
  "$image_file"

loginctl lock-session
