#! /usr/bin/env bash

path=${1:-$PWD}

if [[ ! -x $(command -v unzip ) ]]; then
  >&2 echo 'no unzip found, skipping...'
  exit 1
fi

(
  cd "$path" || exit 1

  find . -maxdepth 1 -type f -name '*.egg' | while read -r egg; do
    zip=${egg//\.egg/.zip}

    if [[ $SHIT_GOT_REAL == x ]]; then
      mv "$egg" "$zip"
      mkdir "$egg"
      unzip -oq "$zip" -d "$egg"
    else
      >&2 echo "mv $egg $zip"
      >&2 echo "mkdir $egg"
      >&2 echo "unzip -oq $zip -d $egg"
    fi
  done
)

